
# 日志中配置信息的日志级别不 ERROR 以下的不打印
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
spring:
  datasource:
    url: jdbc:mysql://8.142.78.63:3306/yu-auth?useUnicode=TRUE&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 2
      pool-name: yu-auth-pool
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
