server:
  port: 10010
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: 100MB
  http2:
    enabled: true

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: dev