
# 日志中配置信息的日志级别不 ERROR 以下的不打印
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yu-auth?useUnicode=TRUE&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 2
      pool-name: yu-auth-pool
      connection-timeout: 30000

