# 日志中配置信息的日志级别不 ERROR 以下的不打印
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR

leaf:
  id:
    addr: http://8.142.78:63:10005/api/snowflake/id/1

# 数据库连接池配置
spring:
  datasource:
    url: jdbc:mysql://8.142.78.63:3306/yu-auth?useUnicode=TRUE&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 2
      pool-name: yu-auth-pool
      connection-timeout: 30000
  #      redis配置``2`前 11111111111111111111111
  redis:
    database: 0
    host: 8.142.78.63
    port: 6379
    password: redis
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  #        邮件配置
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 465
    username: wanghaoxin5277@163.com
    password: SAMDEJICPFWEMAXD
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
zookeeper:
  host: localhost
  port: 2181

auth:
  enable: false